export interface AgencyProgram {
  id: string;
  name: string;
  badge: string;
  desc: string;
  yearActive: string;
  portalUrl?: string;
  emblemIcon: string;
  emblemColor: string;
}

export interface AgencyWithPrograms {
  code: string;
  name: string;
  category: string;
  logo: string;
  portalUrl: string;
  programs: AgencyProgram[];
}

export const AGENCY_PROGRAMS_DATA: AgencyWithPrograms[] = [
  {
    code: 'DSWD',
    name: 'Department of Social Welfare and Development',
    category: 'Social Protection & Poverty Alleviation',
    logo: '/brand/agencies/dswd.png',
    portalUrl: 'https://www.dswd.gov.ph',
    programs: [
      {
        id: 'dswd-4ps',
        name: '4Ps — Pantawid Pamilyang Pilipino',
        badge: 'Flagship CCT',
        desc: 'National poverty reduction & conditional cash grants investing in children education & healthcare.',
        yearActive: 'Active 2026',
        portalUrl: 'https://pantawid.dswd.gov.ph',
        emblemIcon: '👨‍👩‍👧‍👦',
        emblemColor: '#F59E0B',
      },
      {
        id: 'dswd-aics',
        name: 'AICS — Assistance in Crisis Situations',
        badge: 'Medical & Funeral Aid',
        desc: 'Immediate emergency financial, educational, medical, and burial assistance for distressed citizens.',
        yearActive: 'Active 2026',
        portalUrl: 'https://aics.dswd.gov.ph',
        emblemIcon: '🏥',
        emblemColor: '#EF4444',
      },
      {
        id: 'dswd-foodstamp',
        name: 'Walang Gutom 2027 Food Stamp',
        badge: 'Nutrition Support',
        desc: 'Digital electronic benefit cards providing nutritious monthly food credits to food-poor Filipino families.',
        yearActive: 'Active 2026',
        portalUrl: 'https://www.dswd.gov.ph',
        emblemIcon: '🥗',
        emblemColor: '#10B981',
      },
      {
        id: 'dswd-kalahi',
        name: 'KALAHI-CIDSS Community Grants',
        badge: 'Community-Driven',
        desc: 'Empowering barangays to plan, fund, and execute critical local social infrastructure projects.',
        yearActive: 'Active 2026',
        portalUrl: 'https://kalahi.dswd.gov.ph',
        emblemIcon: '🏛️',
        emblemColor: '#38BDF8',
      },
      {
        id: 'dswd-tarabasa',
        name: 'Tara, Basa! Tutoring Program',
        badge: 'Literacy & Youth',
        desc: 'State university youth tutors assisting elementary non-readers while receiving cash-for-work stipends.',
        yearActive: 'Active 2026',
        portalUrl: 'https://www.dswd.gov.ph',
        emblemIcon: '📖',
        emblemColor: '#8B5CF6',
      },
      {
        id: 'dswd-slp',
        name: 'Sustainable Livelihood Program (SLP)',
        badge: 'Micro-Enterprise',
        desc: 'Seed capital grants and technical skills training for sustainable community micro-enterprises.',
        yearActive: 'Active 2026',
        portalUrl: 'https://slp.dswd.gov.ph',
        emblemIcon: '💼',
        emblemColor: '#F97316',
      },
      {
        id: 'dswd-socpen',
        name: 'Social Pension for Indigent Seniors',
        badge: 'Senior Citizens',
        desc: 'Monthly cash stipend of ₱1,000 to augment daily subsistence and medical needs of indigent elderly.',
        yearActive: 'Active 2026',
        portalUrl: 'https://www.dswd.gov.ph',
        emblemIcon: '👴',
        emblemColor: '#06B6D4',
      },
      {
        id: 'dswd-centenarian',
        name: 'Centenarians Act & Octogenarian Aid',
        badge: 'Elderly Welfare',
        desc: '₱100,000 centenarian cash gifts plus expanded benefits for senior citizens turning 80, 85, 90, & 95.',
        yearActive: 'Active 2026',
        portalUrl: 'https://www.dswd.gov.ph',
        emblemIcon: '🎖️',
        emblemColor: '#EAB308',
      },
    ],
  },
  {
    code: 'DepEd',
    name: 'Department of Education',
    category: 'Basic Education & Youth',
    logo: '/brand/agencies/deped.png',
    portalUrl: 'https://www.deped.gov.ph',
    programs: [
      {
        id: 'deped-matatag',
        name: 'MATATAG Curriculum 2026',
        badge: 'Core Academic',
        desc: 'Decongested foundational basic education curriculum targeting reading literacy and math numeracy.',
        yearActive: 'Active 2026',
        emblemIcon: '📚',
        emblemColor: '#38BDF8',
      },
      {
        id: 'deped-als',
        name: 'Alternative Learning System (ALS 2.0)',
        badge: 'Out-of-School Youth',
        desc: 'Community-based flexible modular learning pathway for second-chance education and career credentialing.',
        yearActive: 'Active 2026',
        emblemIcon: '✏️',
        emblemColor: '#10B981',
      },
      {
        id: 'deped-voucher',
        name: 'Senior High School Voucher Program',
        badge: 'Tuition Subsidy',
        desc: 'Financial subsidies enabling public Grade 10 completers to attend private Senior High Schools.',
        yearActive: 'Active 2026',
        emblemIcon: '🎓',
        emblemColor: '#F59E0B',
      },
      {
        id: 'deped-sbfp',
        name: 'School-Based Feeding Program (SBFP)',
        badge: 'Nutrition Support',
        desc: 'Providing nutritious hot meals and fresh milk to undernourished kindergarten and elementary pupils.',
        yearActive: 'Active 2026',
        emblemIcon: '🥛',
        emblemColor: '#EC4899',
      },
      {
        id: 'deped-digital',
        name: 'DepEd Computerization & DigiRise',
        badge: 'Digital Classrooms',
        desc: 'Deploying smart interactive screens, laptops, and offline digital content servers nationwide.',
        yearActive: 'Active 2026',
        emblemIcon: '💻',
        emblemColor: '#6366F1',
      },
    ],
  },
  {
    code: 'DOH',
    name: 'Department of Health',
    category: 'Universal Health Care & Hospitals',
    logo: '/brand/agencies/doh.png',
    portalUrl: 'https://doh.gov.ph',
    programs: [
      {
        id: 'doh-malasakit',
        name: 'Malasakit Centers One-Stop Shop',
        badge: 'Zero-Balance Bill',
        desc: 'Consolidating PhilHealth, DOH MAIP, PCSO, and DSWD medical aid into one hospital desk.',
        yearActive: 'Active 2026',
        emblemIcon: '🩺',
        emblemColor: '#EF4444',
      },
      {
        id: 'doh-konsulta',
        name: 'PhilHealth Konsulta Package',
        badge: 'Primary Care',
        desc: 'Free outpatient primary consultations, 13 targeted laboratory exams, and 21 essential maintenance medicines.',
        yearActive: 'Active 2026',
        emblemIcon: '💊',
        emblemColor: '#10B981',
      },
      {
        id: 'doh-maip',
        name: 'Medical Assistance to Indigent Patients (MAIP)',
        badge: 'Hospital Subsidies',
        desc: 'Hospital bill coverage for medicines, diagnostic tests, surgeries, and specialized medical procedures.',
        yearActive: 'Active 2026',
        emblemIcon: '🚑',
        emblemColor: '#38BDF8',
      },
      {
        id: 'doh-immunization',
        name: 'National Immunization & Bakuna Eskwela',
        badge: 'Public Health',
        desc: 'Free nationwide routine vaccines for infants and school-based immunization for children.',
        yearActive: 'Active 2026',
        emblemIcon: '💉',
        emblemColor: '#F59E0B',
      },
    ],
  },
  {
    code: 'DOLE',
    name: 'Department of Labor and Employment',
    category: 'Labor & Worker Rights',
    logo: '/brand/agencies/dole.png',
    portalUrl: 'https://www.dole.gov.ph',
    programs: [
      {
        id: 'dole-tupad',
        name: 'TUPAD Emergency Community Work',
        badge: 'Displaced Workers',
        desc: 'Emergency community employment for 10–30 days paying prevailing regional minimum wages.',
        yearActive: 'Active 2026',
        emblemIcon: '👷',
        emblemColor: '#F59E0B',
      },
      {
        id: 'dole-spes',
        name: 'SPES — Special Employment for Students',
        badge: 'Youth & Students',
        desc: 'Bridging financial needs of poor but deserving students through paid government and private apprenticeships.',
        yearActive: 'Active 2026',
        emblemIcon: '🧑‍🎓',
        emblemColor: '#38BDF8',
      },
      {
        id: 'dole-gip',
        name: 'Government Internship Program (GIP)',
        badge: 'Civil Service Entry',
        desc: '3 to 6-month paid internships in government agencies preparing youth for civil service careers.',
        yearActive: 'Active 2026',
        emblemIcon: '📋',
        emblemColor: '#10B981',
      },
    ],
  },
  {
    code: 'DPWH',
    name: 'Department of Public Works and Highways',
    category: 'Public Infrastructure',
    logo: '/brand/agencies/dpwh.png',
    portalUrl: 'https://www.dpwh.gov.ph',
    programs: [
      {
        id: 'dpwh-bbm',
        name: 'Build Better More Infrastructure',
        badge: 'National Arterial',
        desc: 'Massive expressway, bypass roads, and inter-island connectivity projects modernizing PH transport.',
        yearActive: 'Active 2026',
        emblemIcon: '🏗️',
        emblemColor: '#F97316',
      },
      {
        id: 'dpwh-cssp',
        name: 'Convergence and Special Support Program',
        badge: 'Regional Access',
        desc: 'Roads leading to tourism destinations, agricultural economic zones, airports, and seaports.',
        yearActive: 'Active 2026',
        emblemIcon: '🛣️',
        emblemColor: '#10B981',
      },
    ],
  },
  {
    code: 'BIR',
    name: 'Bureau of Internal Revenue',
    category: 'National Tax Administration',
    logo: '/brand/agencies/bir.png',
    portalUrl: 'https://www.bir.gov.ph',
    programs: [
      {
        id: 'bir-eopt',
        name: 'Ease of Paying Taxes (EOPT Act 2026)',
        badge: 'Tax Modernization',
        desc: 'Seamless file-and-pay anywhere policy, simplified micro-business classifications, and reduced invoice penalties.',
        yearActive: 'Active 2026',
        emblemIcon: '🧾',
        emblemColor: '#38BDF8',
      },
      {
        id: 'bir-orus',
        name: 'ORUS — Online Registration & Updates',
        badge: 'Digital TIN & Books',
        desc: 'End-to-end web portal for TIN issuance, business registration certificates, and digital stamp processing.',
        yearActive: 'Active 2026',
        emblemIcon: '💻',
        emblemColor: '#10B981',
      },
    ],
  },
  {
    code: 'BOC',
    name: 'Bureau of Customs',
    category: 'Border & Tariff Control',
    logo: '/brand/agencies/boc.png',
    portalUrl: 'https://customs.gov.ph',
    programs: [
      {
        id: 'boc-nsw',
        name: 'National Single Window 3.0',
        badge: 'Trade Clearance',
        desc: 'Integrated inter-agency digital portal for automated import and export permits clearance.',
        yearActive: 'Active 2026',
        emblemIcon: '🚢',
        emblemColor: '#0284C7',
      },
      {
        id: 'boc-etracc',
        name: 'E-TRACC Container GPS Monitoring',
        badge: 'Anti-Smuggling',
        desc: 'Real-time electronic tracking of containerized cargo moving between freeports and customs warehouses.',
        yearActive: 'Active 2026',
        emblemIcon: '📦',
        emblemColor: '#F59E0B',
      },
    ],
  },
  {
    code: 'DICT',
    name: 'Department of Information and Communications Technology',
    category: 'Digital Governance & ICT',
    logo: '/brand/agencies/dict.png',
    portalUrl: 'https://dict.gov.ph',
    programs: [
      {
        id: 'dict-egov',
        name: 'eGov PH Super App',
        badge: 'Citizen One-Stop',
        desc: 'Unified mobile platform for government IDs, travel declarations, clearances, and national social services.',
        yearActive: 'Active 2026',
        emblemIcon: '📱',
        emblemColor: '#38BDF8',
      },
      {
        id: 'dict-freewifi',
        name: 'Free Wi-Fi for All Program',
        badge: 'Public Internet',
        desc: 'Free satellite and fiber broadband hotspots in public plazas, rural clinics, transport terminals, and schools.',
        yearActive: 'Active 2026',
        emblemIcon: '📶',
        emblemColor: '#10B981',
      },
    ],
  },
  {
    code: 'CSC',
    name: 'Civil Service Commission',
    category: 'Constitutional Commission',
    logo: '/brand/agencies/csc.png',
    portalUrl: 'https://csc.gov.ph',
    programs: [
      {
        id: 'csc-pds2026',
        name: 'Revised 2026 CS Form 212 Portal',
        badge: 'Civil Service PDS',
        desc: 'New standardized 4-page Personal Data Sheet and Work Experience Sheet (WES) for all plantilla appointments.',
        yearActive: 'Active 2026',
        emblemIcon: '📑',
        emblemColor: '#F59E0B',
      },
      {
        id: 'csc-cse',
        name: 'Civil Service Exam Online Booking',
        badge: 'Eligibility',
        desc: 'Online application and scheduling system for Professional and SubProfessional Career Service Exams.',
        yearActive: 'Active 2026',
        emblemIcon: '📝',
        emblemColor: '#38BDF8',
      },
    ],
  },
  {
    code: 'DBM',
    name: 'Department of Budget and Management',
    category: 'Fiscal Administration',
    logo: '/brand/agencies/dbm.png',
    portalUrl: 'https://www.dbm.gov.ph',
    programs: [
      {
        id: 'dbm-btms',
        name: 'Budget & Treasury Management System (BTMS)',
        badge: 'Public Finance',
        desc: 'Centralized web system tracking national budget disbursements and appropriations in real-time.',
        yearActive: 'Active 2026',
        emblemIcon: '📊',
        emblemColor: '#10B981',
      },
      {
        id: 'dbm-philgeps',
        name: 'Modernized PhilGEPS 2026',
        badge: 'e-Procurement',
        desc: 'Fully electronic government procurement system ensuring transparency and competitive bidding.',
        yearActive: 'Active 2026',
        emblemIcon: '🛒',
        emblemColor: '#F59E0B',
      },
    ],
  },
  {
    code: 'NEDA',
    name: 'National Economic and Development Authority',
    category: 'Socio-Economic Planning',
    logo: '/brand/agencies/neda.svg',
    portalUrl: 'https://neda.gov.ph',
    programs: [
      {
        id: 'neda-pdp',
        name: 'Philippine Development Plan 2023–2028',
        badge: 'National Strategy',
        desc: 'Transformational blueprint creating green jobs, reducing poverty, and accelerating economic resilience.',
        yearActive: 'Active 2026',
        emblemIcon: '📈',
        emblemColor: '#38BDF8',
      },
      {
        id: 'neda-ifp',
        name: 'Infrastructure Flagship Projects (IFPs)',
        badge: 'Capital Projects',
        desc: 'Monitoring 198 national high-impact infrastructure projects prioritized for rapid socioeconomic return.',
        yearActive: 'Active 2026',
        emblemIcon: '🏗️',
        emblemColor: '#F97316',
      },
    ],
  },
  {
    code: 'DMW',
    name: 'Department of Migrant Workers',
    category: 'OFW Welfare & Services',
    logo: '/brand/agencies/dmw.png',
    portalUrl: 'https://dmw.gov.ph',
    programs: [
      {
        id: 'dmw-ereg',
        name: 'OFW e-Registration System',
        badge: 'Digital OEC',
        desc: 'Paperless digital Overseas Employment Certificate (OEC) and online pre-employment verification.',
        yearActive: 'Active 2026',
        emblemIcon: '✈️',
        emblemColor: '#38BDF8',
      },
      {
        id: 'dmw-kalinga',
        name: 'Agarang Kalinga sa OFW Fund',
        badge: 'Emergency Assistance',
        desc: 'Swift repatriation, legal aid, and financial support for distressed overseas workers and their families.',
        yearActive: 'Active 2026',
        emblemIcon: '🤝',
        emblemColor: '#EF4444',
      },
    ],
  },
  {
    code: 'DA',
    name: 'Department of Agriculture',
    category: 'Food Security & Agri-Fisheries',
    logo: '/brand/agencies/da.png',
    portalUrl: 'https://da.gov.ph',
    programs: [
      {
        id: 'da-kadiwa',
        name: 'Kadiwa ng Pangulo Market Centers',
        badge: 'Direct-to-Consumer',
        desc: 'Connecting farmers and fisherfolk directly to consumers to deliver fresh food at affordable farmgate prices.',
        yearActive: 'Active 2026',
        emblemIcon: '🌾',
        emblemColor: '#10B981',
      },
    ],
  },
  {
    code: 'DOST',
    name: 'Department of Science and Technology',
    category: 'Science, Technology & Innovation',
    logo: '/brand/agencies/dost.png',
    portalUrl: 'https://www.dost.gov.ph',
    programs: [
      {
        id: 'dost-setup',
        name: 'SETUP — Small Enterprise Upgrading',
        badge: 'MSME Innovation',
        desc: 'Technology acquisition loans and product testing facilities modernizing homegrown micro-enterprises.',
        yearActive: 'Active 2026',
        emblemIcon: '🔬',
        emblemColor: '#38BDF8',
      },
    ],
  },
  {
    code: 'DOTr',
    name: 'Department of Transportation',
    category: 'Transit & Mass Mobility',
    logo: '/brand/agencies/dotr.png',
    portalUrl: 'https://dotr.gov.ph',
    programs: [
      {
        id: 'dotr-subway',
        name: 'Metro Manila Subway Project',
        badge: 'Mega Transit',
        desc: 'Philippines first underground mass transit railway line connecting Valenzuela to NAIA airport.',
        yearActive: 'Active 2026',
        emblemIcon: '🚇',
        emblemColor: '#3B82F6',
      },
    ],
  },
  {
    code: 'DENR',
    name: 'Department of Environment and Natural Resources',
    category: 'Environment & Forestry',
    logo: '/brand/agencies/denr.png',
    portalUrl: 'https://denr.gov.ph',
    programs: [
      {
        id: 'denr-ngp',
        name: 'National Greening Program (Enhanced)',
        badge: 'Reforestation',
        desc: 'Community-partnered tree planting, bamboo plantation development, and coastal mangrove restoration.',
        yearActive: 'Active 2026',
        emblemIcon: '🌲',
        emblemColor: '#059669',
      },
    ],
  },
  {
    code: 'DTI',
    name: 'Department of Trade and Industry',
    category: 'Commerce, Industry & Investment',
    logo: '/brand/agencies/dti.png',
    portalUrl: 'https://www.dti.gov.ph',
    programs: [
      {
        id: 'dti-negosyo',
        name: 'Negosyo Centers Nationwide',
        badge: 'Business Startup',
        desc: 'Over 1,400 one-stop shops facilitating business registration, mentorship, and financing for MSMEs.',
        yearActive: 'Active 2026',
        emblemIcon: '🏪',
        emblemColor: '#F59E0B',
      },
    ],
  },
  {
    code: 'DILG',
    name: 'Department of the Interior and Local Government',
    category: 'Local Governance & Peace',
    logo: '/brand/agencies/dilg.png',
    portalUrl: 'https://www.dilg.gov.ph',
    programs: [
      {
        id: 'dilg-sglg',
        name: 'Seal of Good Local Governance (SGLG)',
        badge: 'LGU Awards',
        desc: 'National assessment recognizing transparent, accountable, and high-performing local government units.',
        yearActive: 'Active 2026',
        emblemIcon: '🛡️',
        emblemColor: '#38BDF8',
      },
    ],
  },
  {
    code: 'DOF',
    name: 'Department of Finance',
    category: 'Revenue & Fiscal Policy',
    logo: '/brand/agencies/dof.png',
    portalUrl: 'https://www.dof.gov.ph',
    programs: [
      {
        id: 'dof-fiscal',
        name: 'Medium-Term Fiscal Framework 2026',
        badge: 'Fiscal Health',
        desc: 'Strategic economic management reducing national deficit while funding vital public education and health.',
        yearActive: 'Active 2026',
        emblemIcon: '💰',
        emblemColor: '#EAB308',
      },
    ],
  },
  {
    code: 'DOJ',
    name: 'Department of Justice',
    category: 'Legal Affairs & Prosecution',
    logo: '/brand/agencies/doj.png',
    portalUrl: 'https://www.doj.gov.ph',
    programs: [
      {
        id: 'doj-katarungan',
        name: 'Katarungang Pambarangay & Legal Aid',
        badge: 'Swift Justice',
        desc: 'Free legal counseling and community mediation services resolving disputes at the grassroot level.',
        yearActive: 'Active 2026',
        emblemIcon: '⚖️',
        emblemColor: '#38BDF8',
      },
    ],
  },
  {
    code: 'DFA',
    name: 'Department of Foreign Affairs',
    category: 'Diplomatic Service & Consular Affairs',
    logo: '/brand/agencies/dfa.png',
    portalUrl: 'https://dfa.gov.ph',
    programs: [
      {
        id: 'dfa-epassport',
        name: 'e-Passport Online Appointment System',
        badge: 'Consular Services',
        desc: 'Convenient online slot reservation and document verification for Philippine passport issuance.',
        yearActive: 'Active 2026',
        emblemIcon: '📘',
        emblemColor: '#3B82F6',
      },
    ],
  },
  {
    code: 'DOE',
    name: 'Department of Energy',
    category: 'Energy & Power Policy',
    logo: '/brand/agencies/doe.png',
    portalUrl: 'https://doe.gov.ph',
    programs: [
      {
        id: 'doe-renewable',
        name: 'Renewable Energy 2030 Roadmap',
        badge: 'Clean Energy',
        desc: 'Expanding solar, wind, and geothermal micro-grids to achieve 35% renewable power generation.',
        yearActive: 'Active 2026',
        emblemIcon: '⚡',
        emblemColor: '#EAB308',
      },
    ],
  },
  {
    code: 'DND',
    name: 'Department of National Defense',
    category: 'National Security & Civil Defense',
    logo: '/brand/agencies/dnd.png',
    portalUrl: 'https://dnd.gov.ph',
    programs: [
      {
        id: 'dnd-ndrrmc',
        name: 'NDRRMC Disaster Emergency Alert System',
        badge: 'Disaster Preparedness',
        desc: 'Rapid mobile cell broadcast warnings, preemptive evacuation planning, and emergency food stockpiles.',
        yearActive: 'Active 2026',
        emblemIcon: '🚨',
        emblemColor: '#EF4444',
      },
    ],
  },
];
