export type GovernmentJob = {
  id: string;
  title: string;
  agency: string;
  agencyAcronym: string;
  region: string;
  placeOfAssignment: string;
  salaryGrade: number;
  monthlySalary: string;
  itemNumber: string;
  vacancies: number;
  education: string;
  training: string;
  experience: string;
  eligibility: string;
  competency: string;
  deadline: string; // e.g. "Sep 15, 2026"
  isClosingSoon?: boolean;
  isToday?: boolean;
  isNewToday?: boolean;
  postedTime?: string;
  postedDate: string;
  documentsNeeded: string[];
  howToApply: {
    addresseeName: string;
    addresseeTitle: string;
    addresseeOffice: string;
    addresseeAddress: string;
    contactEmail: string;
    contactPhone: string;
    portalUrl: string;
  };
  applicationNotes: string;
  skills: string[];
};

export const GOVERNMENT_JOBS: GovernmentJob[] = [
  {
    id: 'denr-f3-1',
    title: 'Forester III',
    agency: 'Department of Environment and Natural Resources',
    agencyAcronym: 'DENR',
    region: 'Region 2 - Cagayan Valley - Region 2',
    placeOfAssignment: 'PENRO Cagayan / CENRO Alcala',
    salaryGrade: 18,
    monthlySalary: '₱46,725.00',
    itemNumber: 'OSEC-DENRB-FOR3-112-2014',
    vacancies: 1,
    education: "Bachelor's degree in Forestry",
    training: '8 hours of relevant training in forest management and environmental assessment',
    experience: '2 years of relevant experience in forestry administration or forest law enforcement',
    eligibility: 'RA 1080 (Registered Professional Forester)',
    competency: 'Forest protection, watershed management, community-based forest management, GIS mapping',
    deadline: 'Sep 15, 2026',
    isClosingSoon: true,
    isToday: true,
    postedDate: '2026-09-04',
    documentsNeeded: [
      'Signed application letter specifying the Position Title, Item Number, and Office applied for',
      'Fully accomplished and signed Personal Data Sheet (PDS) and Work Experience Sheet (WES) using CS Form No. 212 Revised 2026; digitally signed or electronically signed with recent passport-size photo and 3 Character References',
      'Authenticated copy of Transcript of Records (TOR) and Diploma',
      'Proof of eligibility: RA 1080 Registered Professional Forester (PRC license authenticated copy or LERIS verification screenshot)',
      'Certified photocopies of relevant Training Certificates (8 hours) and Service Record or Certificate of Employment',
    ],
    howToApply: {
      addresseeName: 'ATTY. ISMAEL T. MANALICOD, CESO IV',
      addresseeTitle: 'Regional Executive Director',
      addresseeOffice: 'Regional Office No. 02',
      addresseeAddress: 'Regional Government Center, Carig Sur, Tuguegarao City, Cagayan',
      contactEmail: 'r2@denr.gov.ph',
      contactPhone: '09565774996',
      portalUrl: 'https://systems.r2.denr.gov.ph/jobportal/pages/landing.php',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Forest inventory & survey',
      'GIS mapping & spatial analysis',
      'Environmental impact monitoring',
      'Watershed conservation',
      'Technical report preparation',
      'Community consultations',
      'Forest law enforcement',
    ],
  },
  {
    id: 'denr-f1-1',
    title: 'Forester I',
    agency: 'Department of Environment and Natural Resources',
    agencyAcronym: 'DENR',
    region: 'Region 2 - Cagayan Valley - Region 2',
    placeOfAssignment: 'PENRO Isabela / CENRO Naguilian',
    salaryGrade: 11,
    monthlySalary: '₱27,000.00',
    itemNumber: 'OSEC-DENRB-FOR1-088-2014',
    vacancies: 1,
    education: "Bachelor's degree in Forestry",
    training: 'None required',
    experience: 'None required',
    eligibility: 'RA 1080 (Registered Professional Forester)',
    competency: 'Tree inventory, seedling nursery maintenance, community forestry, forest patrol',
    deadline: 'Sep 15, 2026',
    isClosingSoon: true,
    isToday: true,
    postedDate: '2026-09-04',
    documentsNeeded: [
      'Signed application letter specifying the Position Title, Item Number, and Office applied for',
      'Fully accomplished and signed Personal Data Sheet (PDS) and Work Experience Sheet (WES) using CS Form No. 212 Revised 2026 with recent passport-size photo',
      'Authenticated copy of Transcript of Records (TOR) and College Diploma',
      'Proof of eligibility: RA 1080 (Registered Professional Forester)',
    ],
    howToApply: {
      addresseeName: 'ATTY. ISMAEL T. MANALICOD, CESO IV',
      addresseeTitle: 'Regional Executive Director',
      addresseeOffice: 'Regional Office No. 02',
      addresseeAddress: 'Regional Government Center, Carig Sur, Tuguegarao City, Cagayan',
      contactEmail: 'r2@denr.gov.ph',
      contactPhone: '09565774996',
      portalUrl: 'https://systems.r2.denr.gov.ph/jobportal/pages/landing.php',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Tree species identification',
      'Nursery seedling propagation',
      'GPS & Compass navigation',
      'Field data recording',
      'Community organizing',
      'Basic report writing',
    ],
  },
  {
    id: 'denr-sems-1',
    title: 'Senior Ecosystems Management Specialist',
    agency: 'Department of Environment and Natural Resources',
    agencyAcronym: 'DENR',
    region: 'Region 2 - Cagayan Valley - Region 2',
    placeOfAssignment: 'Conservation and Development Division, Regional Office No. 02',
    salaryGrade: 18,
    monthlySalary: '₱46,725.00',
    itemNumber: 'OSEC-DENRB-SEMS-055-2015',
    vacancies: 1,
    education: "Bachelor's degree relevant to the job (Biology, Environmental Science, Forestry)",
    training: '8 hours of relevant training in biodiversity or coastal resource management',
    experience: '2 years of relevant experience in ecosystems management or protected area administration',
    eligibility: 'Career Service (Professional) / Second Level Eligibility / RA 1080',
    competency: 'Protected area planning, biodiversity assessment, climate change adaptation, policy analysis',
    deadline: 'Sep 15, 2026',
    isClosingSoon: true,
    isToday: true,
    postedDate: '2026-09-04',
    documentsNeeded: [
      'Signed application letter specifying the Position Title, Item Number, and Office applied for',
      'Fully accomplished and signed Personal Data Sheet (PDS) and Work Experience Sheet (WES) using CS Form No. 212 Revised 2026 with recent passport photo',
      'Authenticated copy of Transcript of Records (TOR) and Diploma',
      'Proof of eligibility: CS Professional or RA 1080',
      'Certified photocopies of Training Certificates and Certificate of Employment',
    ],
    howToApply: {
      addresseeName: 'ATTY. ISMAEL T. MANALICOD, CESO IV',
      addresseeTitle: 'Regional Executive Director',
      addresseeOffice: 'Regional Office No. 02',
      addresseeAddress: 'Regional Government Center, Carig Sur, Tuguegarao City, Cagayan',
      contactEmail: 'r2@denr.gov.ph',
      contactPhone: '09565774996',
      portalUrl: 'https://systems.r2.denr.gov.ph/jobportal/pages/landing.php',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Biodiversity assessment',
      'Protected area management planning',
      'Ecological data analysis',
      'Policy paper drafting',
      'Stakeholder consultation facilitation',
      'Scientific research synthesis',
    ],
  },
  {
    id: 'denr-ems2-1',
    title: 'Ecosystems Management Specialist II',
    agency: 'Department of Environment and Natural Resources',
    agencyAcronym: 'DENR',
    region: 'Region 2 - Cagayan Valley - Region 2',
    placeOfAssignment: 'PENRO Quirino / CENRO Diffun',
    salaryGrade: 15,
    monthlySalary: '₱36,619.00',
    itemNumber: 'OSEC-DENRB-EMS2-029-2015',
    vacancies: 1,
    education: "Bachelor's degree relevant to the job (Environmental Science, Biology, Forestry)",
    training: '4 hours of relevant training in environmental monitoring',
    experience: '1 year of relevant experience in environmental and ecosystems management',
    eligibility: 'Career Service (Professional) / Second Level Eligibility',
    competency: 'Water quality monitoring, wildlife flora/fauna tracking, environmental compliance inspection',
    deadline: 'Sep 15, 2026',
    isClosingSoon: true,
    isToday: true,
    postedDate: '2026-09-04',
    documentsNeeded: [
      'Signed application letter specifying the Position Title, Item Number, and Office applied for',
      'Fully accomplished and signed Personal Data Sheet (PDS) and Work Experience Sheet (WES) using CS Form No. 212 Revised 2026',
      'Authenticated copy of Transcript of Records (TOR) and College Diploma',
      'Proof of CS Professional Eligibility Certificate',
      'Training certificates and employment records',
    ],
    howToApply: {
      addresseeName: 'ATTY. ISMAEL T. MANALICOD, CESO IV',
      addresseeTitle: 'Regional Executive Director',
      addresseeOffice: 'Regional Office No. 02',
      addresseeAddress: 'Regional Government Center, Carig Sur, Tuguegarao City, Cagayan',
      contactEmail: 'r2@denr.gov.ph',
      contactPhone: '09565774996',
      portalUrl: 'https://systems.r2.denr.gov.ph/jobportal/pages/landing.php',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Environmental compliance auditing',
      'Water & air sampling techniques',
      'Field survey documentation',
      'Ecosystem mapping',
      'Inter-agency coordination',
    ],
  },
  {
    id: 'denr-acc3-1',
    title: 'Accountant III',
    agency: 'Department of Environment and Natural Resources',
    agencyAcronym: 'DENR',
    region: 'Region 2 - Cagayan Valley - Region 2',
    placeOfAssignment: 'Finance Division, Regional Office No. 02',
    salaryGrade: 19,
    monthlySalary: '₱51,357.00',
    itemNumber: 'OSEC-DENRB-ACC3-009-2015',
    vacancies: 1,
    education: "Bachelor's degree in Commerce / BS Accountancy",
    training: '8 hours of relevant training in government accounting (GAM/COA rules)',
    experience: '2 years of relevant experience in government accounting or auditing',
    eligibility: 'RA 1080 (Certified Public Accountant - CPA)',
    competency: 'Financial statements preparation, eNGAS, budget monitoring, tax compliance, COA rules',
    deadline: 'Sep 15, 2026',
    isClosingSoon: true,
    isToday: true,
    postedDate: '2026-09-04',
    documentsNeeded: [
      'Signed application letter specifying Position Title, Item Number, and Office applied for',
      'Fully accomplished and signed CS Form 212 (Revised 2026) with WES and passport photo',
      'Authenticated Transcript of Records (TOR) and BS Accountancy Diploma',
      'Proof of PRC CPA License (authenticated copy or PRC LERIS screen verification)',
      'Training certificates in Government Accounting Manual (GAM) and COA circulars',
    ],
    howToApply: {
      addresseeName: 'ATTY. ISMAEL T. MANALICOD, CESO IV',
      addresseeTitle: 'Regional Executive Director',
      addresseeOffice: 'Regional Office No. 02',
      addresseeAddress: 'Regional Government Center, Carig Sur, Tuguegarao City, Cagayan',
      contactEmail: 'r2@denr.gov.ph',
      contactPhone: '09565774996',
      portalUrl: 'https://systems.r2.denr.gov.ph/jobportal/pages/landing.php',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Government Accounting Manual (GAM)',
      'eNGAS & eBudget systems',
      'COA audit compliance',
      'Financial statement consolidation',
      'Tax withholding & BIR returns',
      'Disbursement voucher verification',
    ],
  },
  {
    id: 'denr-dmo1-1',
    title: 'Development Management Officer I',
    agency: 'Department of Environment and Natural Resources',
    agencyAcronym: 'DENR',
    region: 'Region 2 - Cagayan Valley - Region 2',
    placeOfAssignment: 'Planning and Management Division, Regional Office No. 02',
    salaryGrade: 11,
    monthlySalary: '₱27,000.00',
    itemNumber: 'OSEC-DENRB-DMO1-041-2015',
    vacancies: 1,
    education: "Bachelor's degree relevant to the job",
    training: 'None required',
    experience: 'None required',
    eligibility: 'Career Service (Professional) / Second Level Eligibility',
    competency: 'Project monitoring, program evaluation, data encoding, statistical collation',
    deadline: 'Sep 15, 2026',
    isClosingSoon: true,
    postedDate: '2026-09-04',
    documentsNeeded: [
      'Signed application letter specifying Position Title, Item Number, and Office applied for',
      'Fully accomplished CS Form No. 212 Revised 2026 with recent passport-size photo and 3 references',
      'Authenticated copy of Transcript of Records (TOR) and College Diploma',
      'Proof of Career Service Professional Eligibility',
    ],
    howToApply: {
      addresseeName: 'ATTY. ISMAEL T. MANALICOD, CESO IV',
      addresseeTitle: 'Regional Executive Director',
      addresseeOffice: 'Regional Office No. 02',
      addresseeAddress: 'Regional Government Center, Carig Sur, Tuguegarao City, Cagayan',
      contactEmail: 'r2@denr.gov.ph',
      contactPhone: '09565774996',
      portalUrl: 'https://systems.r2.denr.gov.ph/jobportal/pages/landing.php',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Project monitoring & evaluation',
      'Data encoding & statistical spreadsheets',
      'Documentation & minutes of meetings',
      'Inter-division coordination',
      'Presentation design',
    ],
  },
  {
    id: 'denr-dmo3-1',
    title: 'Development Management Officer III',
    agency: 'Department of Environment and Natural Resources',
    agencyAcronym: 'DENR',
    region: 'Region 2 - Cagayan Valley - Region 2',
    placeOfAssignment: 'Planning and Management Division, Regional Office No. 02',
    salaryGrade: 18,
    monthlySalary: '₱46,725.00',
    itemNumber: 'OSEC-DENRB-DMO3-018-2015',
    vacancies: 1,
    education: "Bachelor's degree relevant to the job",
    training: '8 hours of relevant training in project management, development planning or monitoring',
    experience: '2 years of relevant experience in development planning, program monitoring or policy analysis',
    eligibility: 'Career Service (Professional) / Second Level Eligibility',
    competency: 'Strategic planning, performance governance system (PGS), budget proposal alignment',
    deadline: 'Sep 15, 2026',
    isClosingSoon: true,
    postedDate: '2026-09-04',
    documentsNeeded: [
      'Signed application letter specifying Position Title, Item Number, and Office applied for',
      'Fully accomplished CS Form 212 (Revised 2026) with WES and passport photo',
      'Authenticated copy of Transcript of Records (TOR) and Diploma',
      'Certificate of Eligibility (CS Professional)',
      'Proof of 8 hours relevant training and 2 years supervisory experience',
    ],
    howToApply: {
      addresseeName: 'ATTY. ISMAEL T. MANALICOD, CESO IV',
      addresseeTitle: 'Regional Executive Director',
      addresseeOffice: 'Regional Office No. 02',
      addresseeAddress: 'Regional Government Center, Carig Sur, Tuguegarao City, Cagayan',
      contactEmail: 'r2@denr.gov.ph',
      contactPhone: '09565774996',
      portalUrl: 'https://systems.r2.denr.gov.ph/jobportal/pages/landing.php',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Strategic development planning',
      'Performance governance system (PGS)',
      'Results-based monitoring & evaluation',
      'Policy brief formulation',
      'Budget program execution',
    ],
  },
  {
    id: 'denr-eng1-1',
    title: 'Engineer I',
    agency: 'Department of Environment and Natural Resources',
    agencyAcronym: 'DENR',
    region: 'Region 2 - Cagayan Valley - Region 2',
    placeOfAssignment: 'Surveys and Mapping Division / Infrastructure Unit',
    salaryGrade: 12,
    monthlySalary: '₱29,165.00',
    itemNumber: 'OSEC-DENRB-ENG1-033-2015',
    vacancies: 1,
    education: "Bachelor's degree in engineering relevant to the job (Geodetic, Civil, or Environmental Engineering)",
    training: 'None required',
    experience: 'None required',
    eligibility: 'RA 1080 (Geodetic Engineer / Civil Engineer / Board Passer)',
    competency: 'Land surveying inspection, AutoCAD, project site monitoring, engineering estimates, GIS',
    deadline: 'Sep 15, 2026',
    isClosingSoon: true,
    postedDate: '2026-09-04',
    documentsNeeded: [
      'Signed application letter specifying the Position Title, Item Number, and Office applied for',
      'Fully accomplished and signed Personal Data Sheet (PDS) and Work Experience Sheet (WES) using CS Form No. 212 Revised 2026; digitally signed or electronically signed. PDS must include a recent passport-size picture and three (3) Character References',
      'Proof of eligibility such as report of rating or license: RA 1080 (Geodetic/Civil Engineer) PRC license (authenticated copy or PRC LERIS screen capture)',
      'Authenticated copy of Transcript of Records (TOR) and Engineering Diploma',
      'Certified photocopies of Training Certificates, Special Orders, Certificate of Employment (if applicable)',
    ],
    howToApply: {
      addresseeName: 'ATTY. ISMAEL T. MANALICOD, CESO IV',
      addresseeTitle: 'Regional Executive Director',
      addresseeOffice: 'Regional Office No. 02',
      addresseeAddress: 'Regional Government Center, Carig Sur, Tuguegarao City Regional Hotline: 09565774996',
      contactEmail: 'r2@denr.gov.ph',
      contactPhone: '09565774996',
      portalUrl: 'https://systems.r2.denr.gov.ph/jobportal/pages/landing.php',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Basic engineering principles',
      'Technical drawing interpretation (AutoCAD)',
      'Project site monitoring & inspection',
      'Data collection and analysis',
      'Engineering report writing',
      'Equipment operation & calibration',
      'Field survey troubleshooting',
    ],
  },
  {
    id: 'denr-dmo2-1',
    title: 'Development Management Officer II',
    agency: 'Department of Environment and Natural Resources',
    agencyAcronym: 'DENR',
    region: 'Region 2 - Cagayan Valley - Region 2',
    placeOfAssignment: 'PENRO Cagayan / CENRO Solana',
    salaryGrade: 15,
    monthlySalary: '₱36,619.00',
    itemNumber: 'OSEC-DENRB-DMO2-021-2015',
    vacancies: 1,
    education: "Bachelor's degree relevant to the job",
    training: '4 hours of relevant training in project monitoring or planning',
    experience: '1 year of relevant experience in development administration',
    eligibility: 'Career Service (Professional) / Second Level Eligibility',
    competency: 'Program monitoring, statistical analysis, technical documentation, stakeholder facilitation',
    deadline: 'Sep 15, 2026',
    isClosingSoon: true,
    postedDate: '2026-09-04',
    documentsNeeded: [
      'Signed application letter specifying Position Title, Item Number, and Office applied for',
      'Fully accomplished CS Form 212 (Revised 2026) with WES and passport photo',
      'Authenticated Transcript of Records (TOR) and Diploma',
      'Proof of CS Professional Eligibility',
      'Training and service records',
    ],
    howToApply: {
      addresseeName: 'ATTY. ISMAEL T. MANALICOD, CESO IV',
      addresseeTitle: 'Regional Executive Director',
      addresseeOffice: 'Regional Office No. 02',
      addresseeAddress: 'Regional Government Center, Carig Sur, Tuguegarao City, Cagayan',
      contactEmail: 'r2@denr.gov.ph',
      contactPhone: '09565774996',
      portalUrl: 'https://systems.r2.denr.gov.ph/jobportal/pages/landing.php',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Project implementation monitoring',
      'Database management',
      'Statistical reporting',
      'Community dialogue',
      'Administrative coordination',
    ],
  },
  {
    id: 'denr-math-1',
    title: 'Mathematician Aide I',
    agency: 'Department of Environment and Natural Resources',
    agencyAcronym: 'DENR',
    region: 'Region 2 - Cagayan Valley - Region 2',
    placeOfAssignment: 'Surveys and Mapping Division, Regional Office No. 02',
    salaryGrade: 4,
    monthlySalary: '₱15,586.00',
    itemNumber: 'OSEC-DENRB-MATA1-008-2015',
    vacancies: 1,
    education: 'Completion of two years studies in college or High School Graduate with relevant vocational course',
    training: 'None required',
    experience: 'None required',
    eligibility: 'Career Service (Subprofessional) / First Level Eligibility',
    competency: 'Mathematical computation, technical plotting, records indexing, cadastral coordinate encoding',
    deadline: 'Sep 15, 2026',
    isClosingSoon: true,
    postedDate: '2026-09-04',
    documentsNeeded: [
      'Signed application letter specifying Position Title, Item Number, and Office applied for',
      'Fully accomplished CS Form 212 (Revised 2026) with passport photo',
      'Transcript of Records / High School Diploma & Form 137',
      'Certificate of Subprofessional Eligibility',
    ],
    howToApply: {
      addresseeName: 'ATTY. ISMAEL T. MANALICOD, CESO IV',
      addresseeTitle: 'Regional Executive Director',
      addresseeOffice: 'Regional Office No. 02',
      addresseeAddress: 'Regional Government Center, Carig Sur, Tuguegarao City, Cagayan',
      contactEmail: 'r2@denr.gov.ph',
      contactPhone: '09565774996',
      portalUrl: 'https://systems.r2.denr.gov.ph/jobportal/pages/landing.php',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Mathematical computation & plotting',
      'Cadastral record indexing',
      'Data verification',
      'Records archiving',
      'Spreadsheet encoding',
    ],
  },

  // NEW JOBS TODAY (Image 1 match)
  {
    id: 'ocd-cdo5-1',
    title: 'Civil Defense Officer V',
    agency: 'Office of Civil Defense - Department of National Defense',
    agencyAcronym: 'OCD-DND',
    region: 'Region 8 - Eastern Visayas',
    placeOfAssignment: 'Regional Disaster Risk Reduction and Management Center (RDRRMC 8)',
    salaryGrade: 24,
    monthlySalary: '₱88,410.00',
    itemNumber: 'DND-OCDB-CDO5-003-2016',
    vacancies: 1,
    education: "Master's degree or Certificate in Leadership and Management from CSC",
    training: '40 hours of supervisory/management learning and development',
    experience: '4 years of supervisory experience in disaster risk reduction or emergency response',
    eligibility: 'Career Service (Professional) / Second Level Eligibility',
    competency: 'Incident Command System (ICS), emergency operations center operations, disaster response coordination',
    deadline: 'Sep 25, 2026',
    isNewToday: true,
    postedTime: 'Posted 1:27 PM',
    postedDate: '2026-09-15',
    documentsNeeded: [
      'Signed application letter specifying the Position Title, Item Number, and Office applied for',
      'Fully accomplished CS Form 212 (Revised 2026) with WES and passport photo',
      'Authenticated Masteral TOR and Diploma',
      'CSC Eligibility Certificate',
      'Proof of 40 hours supervisory training and 4 years supervisory experience',
    ],
    howToApply: {
      addresseeName: 'DIR. LORD BYRON P. TORRECARION',
      addresseeTitle: 'Regional Director',
      addresseeOffice: 'Office of Civil Defense Regional Office VIII',
      addresseeAddress: 'Camp Downes, Ormoc City / Government Center, Palo, Leyte',
      contactEmail: 'ocd8@ocd.gov.ph',
      contactPhone: '09171234567',
      portalUrl: 'https://ocd.gov.ph/careers',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Incident Command System (ICS)',
      'Disaster risk reduction governance',
      'Crisis leadership & rapid assessment',
      'Inter-agency command post management',
      'Comprehensive reporting & briefing',
    ],
  },
  {
    id: 'ocd-cdo4-1',
    title: 'Civil Defense Officer IV',
    agency: 'Office of Civil Defense - Department of National Defense',
    agencyAcronym: 'OCD-DND',
    region: 'Region 8 - Eastern Visayas',
    placeOfAssignment: 'Operations Division, Regional Office VIII',
    salaryGrade: 22,
    monthlySalary: '₱71,511.00',
    itemNumber: 'DND-OCDB-CDO4-007-2016',
    vacancies: 1,
    education: "Bachelor's degree relevant to the job",
    training: '16 hours of relevant training in DRRM',
    experience: '3 years of relevant experience in emergency management',
    eligibility: 'Career Service (Professional) / Second Level Eligibility',
    competency: 'Emergency operations coordination, contingency planning, logistics mobilization',
    deadline: 'Sep 25, 2026',
    isNewToday: true,
    postedTime: 'Posted 1:26 PM',
    postedDate: '2026-09-15',
    documentsNeeded: [
      'Signed application letter specifying Position Title, Item Number, and Office applied for',
      'Fully accomplished CS Form 212 (Revised 2026) with WES and passport photo',
      'Authenticated College TOR and Diploma',
      'CSC Eligibility Certificate',
      '16 hours DRRM training certificates',
    ],
    howToApply: {
      addresseeName: 'DIR. LORD BYRON P. TORRECARION',
      addresseeTitle: 'Regional Director',
      addresseeOffice: 'Office of Civil Defense Regional Office VIII',
      addresseeAddress: 'Government Center, Palo, Leyte',
      contactEmail: 'ocd8@ocd.gov.ph',
      contactPhone: '09171234567',
      portalUrl: 'https://ocd.gov.ph/careers',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Contingency plan formulation',
      'Operations center protocols',
      'Relief goods logistics mobilization',
      'Disaster telemetry analysis',
      'Emergency communications',
    ],
  },
  {
    id: 'ocd-cdo3-1',
    title: 'Civil Defense Officer III',
    agency: 'Office of Civil Defense - Department of National Defense',
    agencyAcronym: 'OCD-DND',
    region: 'Region 8 - Eastern Visayas',
    placeOfAssignment: 'Rehabilitation and Recovery Section, Regional Office VIII',
    salaryGrade: 18,
    monthlySalary: '₱46,725.00',
    itemNumber: 'DND-OCDB-CDO3-014-2016',
    vacancies: 2,
    education: "Bachelor's degree relevant to the job",
    training: '8 hours of relevant training in post-disaster needs assessment',
    experience: '2 years of relevant experience in disaster rehabilitation',
    eligibility: 'Career Service (Professional) / Second Level Eligibility',
    competency: 'Post-disaster needs assessment (PDNA), rehabilitation planning, infrastructure assessment',
    deadline: 'Sep 25, 2026',
    isNewToday: true,
    postedTime: 'Posted 1:25 PM',
    postedDate: '2026-09-15',
    documentsNeeded: [
      'Signed application letter specifying Position Title, Item Number, and Office applied for',
      'Fully accomplished CS Form 212 (Revised 2026) with WES and passport photo',
      'Authenticated College TOR and Diploma',
      'CSC Eligibility Certificate',
    ],
    howToApply: {
      addresseeName: 'DIR. LORD BYRON P. TORRECARION',
      addresseeTitle: 'Regional Director',
      addresseeOffice: 'Office of Civil Defense Regional Office VIII',
      addresseeAddress: 'Government Center, Palo, Leyte',
      contactEmail: 'ocd8@ocd.gov.ph',
      contactPhone: '09171234567',
      portalUrl: 'https://ocd.gov.ph/careers',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Post-Disaster Needs Assessment (PDNA)',
      'Damage assessment and loss estimation',
      'Recovery project planning',
      'LGU assistance delivery',
      'Monitoring & evaluation',
    ],
  },
  {
    id: 'ocd-cdo2-1',
    title: 'Civil Defense Officer II',
    agency: 'Office of Civil Defense - Department of National Defense',
    agencyAcronym: 'OCD-DND',
    region: 'Region 8 - Eastern Visayas',
    placeOfAssignment: 'Capacity Building and Training Section, Regional Office VIII',
    salaryGrade: 15,
    monthlySalary: '₱36,619.00',
    itemNumber: 'DND-OCDB-CDO2-022-2016',
    vacancies: 1,
    education: "Bachelor's degree relevant to the job",
    training: '4 hours of relevant training',
    experience: '1 year of relevant experience in training facilitation or DRRM',
    eligibility: 'Career Service (Professional) / Second Level Eligibility',
    competency: 'Community DRRM module delivery, training facilitation, module preparation',
    deadline: 'Sep 25, 2026',
    isNewToday: true,
    postedTime: 'Posted 1:24 PM',
    postedDate: '2026-09-15',
    documentsNeeded: [
      'Signed application letter specifying Position Title, Item Number, and Office applied for',
      'Fully accomplished CS Form 212 (Revised 2026) with WES and passport photo',
      'Authenticated College TOR and Diploma',
      'CSC Eligibility Certificate',
    ],
    howToApply: {
      addresseeName: 'DIR. LORD BYRON P. TORRECARION',
      addresseeTitle: 'Regional Director',
      addresseeOffice: 'Office of Civil Defense Regional Office VIII',
      addresseeAddress: 'Government Center, Palo, Leyte',
      contactEmail: 'ocd8@ocd.gov.ph',
      contactPhone: '09171234567',
      portalUrl: 'https://ocd.gov.ph/careers',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Training design & module development',
      'Public speaking & lecturing',
      'Simulation drill execution',
      'Participant evaluation reporting',
      'Community engagement',
    ],
  },
  {
    id: 'ocd-eng2-1',
    title: 'Engineer II',
    agency: 'Office of Civil Defense - Department of National Defense',
    agencyAcronym: 'OCD-DND',
    region: 'Region 8 - Eastern Visayas',
    placeOfAssignment: 'Disaster Prevention and Mitigation Division',
    salaryGrade: 16,
    monthlySalary: '₱39,672.00',
    itemNumber: 'DND-OCDB-ENG2-005-2016',
    vacancies: 1,
    education: "Bachelor's degree in Civil Engineering",
    training: '4 hours of relevant training in structural or civil works assessment',
    experience: '1 year of relevant experience in structural inspection or civil engineering',
    eligibility: 'RA 1080 (Civil Engineer)',
    competency: 'Structural integrity assessment, flood mitigation appraisal, slope stability review, CAD modeling',
    deadline: 'Sep 25, 2026',
    isNewToday: true,
    postedTime: 'Posted 1:23 PM',
    postedDate: '2026-09-15',
    documentsNeeded: [
      'Signed application letter specifying Position Title, Item Number, and Office applied for',
      'Fully accomplished CS Form 212 (Revised 2026) with WES and passport photo',
      'Authenticated Civil Engineering TOR and Diploma',
      'PRC Civil Engineer License (authenticated copy or LERIS verification)',
    ],
    howToApply: {
      addresseeName: 'DIR. LORD BYRON P. TORRECARION',
      addresseeTitle: 'Regional Director',
      addresseeOffice: 'Office of Civil Defense Regional Office VIII',
      addresseeAddress: 'Government Center, Palo, Leyte',
      contactEmail: 'ocd8@ocd.gov.ph',
      contactPhone: '09171234567',
      portalUrl: 'https://ocd.gov.ph/careers',
    },
    applicationNotes: 'APPLICATIONS WITH INCOMPLETE DOCUMENTS SHALL NOT BE ENTERTAINED.',
    skills: [
      'Structural safety evaluation',
      'AutoCAD & structural modeling',
      'Cost estimation & bill of materials',
      'Site risk assessment',
      'Technical report preparation',
    ],
  },
];

export const TOP_HIRING_AGENCIES = [
  {
    name: 'Philippine Information Agency (PIA)',
    jobsCount: 22,
    code: 'PIA',
  },
  {
    name: 'Department of Environment and Natural Resources (DENR)',
    jobsCount: 20,
    code: 'DENR',
  },
  {
    name: 'Jose B. Lingad Memorial General Hospital (JBLMGH)',
    jobsCount: 12,
    code: 'JBLMGH',
  },
  {
    name: 'Office of Civil Defense - Department of National Defense (OCD-DND)',
    jobsCount: 6,
    code: 'OCD-DND',
  },
  {
    name: 'National Authority for Child Care (NACC)',
    jobsCount: 1,
    code: 'NACC',
  },
];

export const PHILIPPINE_REGIONS = [
  'Region 1 - Ilocos',
  'Region 2 - Cagayan Valley',
  'Region 3 - Central Luzon',
  'Region 4A - CALABARZON',
  'Region 4B - MIMAROPA',
  'Region 5 - Bicol',
  'Region 6 - Western Visayas',
  'Region 7 - Central Visayas',
  'Region 8 - Eastern Visayas',
  'Region 9 - Zamboanga Peninsula',
  'Region 10 - Northern Mindanao',
  'Region 11 - Davao Region',
  'Region 12 - SOCCSKSARGEN',
  'Region 13 - Caraga',
  'NCR - National Capital Region',
  'CAR - Cordillera Administrative Region',
  'BARMM - Bangsamoro',
];

export const GUIDES_AND_RESOURCES = [
  {
    id: 'how-to-fill-out-pds',
    tag: 'GUIDES',
    title: 'How to Fill Out Your PDS',
    excerpt: 'Step-by-step guide to completing your Personal Data Sheet (CS Form 212) correctly.',
    readTime: '6 min read',
    url: '/builder',
  },
  {
    id: 'how-to-write-application-letter',
    tag: 'GUIDES',
    title: 'How to Write an Application Letter',
    excerpt: 'Learn how to create a strong government application letter that stands out to hiring committees.',
    readTime: '5 min read',
    url: '/jobs',
  },
  {
    id: 'salary-grade-2026',
    tag: 'GUIDES',
    title: 'Salary Grade 2026 Philippines: Complete Salary Grade Table (Third Tranche)',
    excerpt: 'The Department of Budget and Management (DBM) has released the official Salary Grade 2026 table under the Third Tranche salary standardization law.',
    readTime: '8 min read',
    url: '/jobs',
  },
  {
    id: 'csc-form-212-revised-2026-guide',
    tag: 'GUIDES',
    title: 'CSC Form 212 Revised 2026: Complete Guide to the Personal Data Sheet (PDS)',
    excerpt: 'Learn everything about CSC Form 212 Revised 2026, including how to properly fill out the Personal Data Sheet, required attachments, and common mistakes.',
    readTime: '10 min read',
    url: '/builder',
  },
  {
    id: 'best-websites-portals-gov-jobs',
    tag: 'RESOURCES',
    title: 'Best Websites and Portals for Finding Government Jobs in the Philippines (2026 Guide)',
    excerpt: 'Looking for legitimate government job openings in the Philippines? Discover the best websites, portals, and official agency career portals.',
    readTime: '7 min read',
    url: '/jobs',
  },
  {
    id: 'csc-requirements-gov-job-applications',
    tag: 'GUIDES',
    title: 'CSC Requirements for Government Job Applications (Complete 2026 Guide)',
    excerpt: 'Learn the complete list of CSC requirements for applying to government jobs in the Philippines, including PDS, eligibility, WES, and certifications.',
    readTime: '6 min read',
    url: '/builder',
  },
];
